version: "3.9"
services:
 web_api:
  build: backend
  container_name: library_api
  ports:
     - 5000:80
  environment:
   - ASPNETCORE_ENVIRONMENT=Development
 frontend:
    build: frontend
    container_name: library_ui
    ports:
      - 3000:3000 
 sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server
    ports:
      - 9000:1433
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
      - MSSQL_PID=Express